/* Generated by Pyrex 0.9.9 on Sun Dec 14 19:52:40 2014 */

#define PY_SSIZE_T_CLEAN
#include "Python.h"
#include "structmember.h"
#ifndef PY_LONG_LONG
  #define PY_LONG_LONG LONG_LONG
#endif
#if PY_VERSION_HEX < 0x02050000
  typedef int Py_ssize_t;
  #define PY_SSIZE_T_MAX INT_MAX
  #define PY_SSIZE_T_MIN INT_MIN
  #define PyInt_FromSsize_t(z) PyInt_FromLong(z)
  #define PyInt_AsSsize_t(o)	PyInt_AsLong(o)
#endif
#if !defined(WIN32) && !defined(MS_WINDOWS)
  #ifndef __stdcall
    #define __stdcall
  #endif
  #ifndef __cdecl
    #define __cdecl
  #endif
#endif
#ifdef __cplusplus
#define __PYX_EXTERN_C extern "C"
#else
#define __PYX_EXTERN_C extern
#endif
#include <math.h>


typedef struct {PyObject **p; int i; char *s; long n;} __Pyx_StringTabEntry; /*proto*/

static PyObject *__pyx_m;
static PyObject *__pyx_b;
static int __pyx_lineno;
static char *__pyx_filename;
static char **__pyx_f;

static int __Pyx_InitStrings(__Pyx_StringTabEntry *t); /*proto*/

static PyObject *__Pyx_Import(PyObject *name, PyObject *from_list); /*proto*/

static void __Pyx_AddTraceback(char *funcname); /*proto*/

/* Declarations from bx.seq._nib */


/* Declarations from implementation of bx.seq._nib */

static char *__pyx_v_2bx_3seq_4_nib_NIB_I2C_TABLE_FIRST;
static char *__pyx_v_2bx_3seq_4_nib_NIB_I2C_TABLE_SECOND;

static char __pyx_k1[] = "struct";
static char __pyx_k2[] = "sys";
static char __pyx_k3[] = "TTTTTTTTTTTTTTTTCCCCCCCCCCCCCCCCAAAAAAAAAAAAAAAAGGGGGGGGGGGGGGGGNNNNNNNNNNNNNNNNXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXttttttttttttttttccccccccccccccccaaaaaaaaaaaaaaaaggggggggggggggggnnnnnnnnnnnnnnnnxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx";
static char __pyx_k4[] = "TCAGNXXXtcagnxxxTCAGNXXXtcagnxxxTCAGNXXXtcagnxxxTCAGNXXXtcagnxxxTCAGNXXXtcagnxxxTCAGNXXXtcagnxxxTCAGNXXXtcagnxxxTCAGNXXXtcagnxxxTCAGNXXXtcagnxxxTCAGNXXXtcagnxxxTCAGNXXXtcagnxxxTCAGNXXXtcagnxxxTCAGNXXXtcagnxxxTCAGNXXXtcagnxxxTCAGNXXXtcagnxxxTCAGNXXXtcagnxxx";

static PyObject *__pyx_n_struct;
static PyObject *__pyx_n_sys;


static __Pyx_StringTabEntry __pyx_string_tab[] = {
  {&__pyx_n_struct, 1, __pyx_k1, sizeof(__pyx_k1)},
  {&__pyx_n_sys, 1, __pyx_k2, sizeof(__pyx_k2)},
  {0, 0, 0, 0}
};



/* Implementation of bx.seq._nib */

static PyObject *__pyx_f_2bx_3seq_4_nib_translate_raw_data(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static char __pyx_doc_2bx_3seq_4_nib_translate_raw_data[] = "\n    Data is a block read from the file that needs to be unpacked, dealing\n    with end conditions based on start/length.\n    ";
static PyObject *__pyx_f_2bx_3seq_4_nib_translate_raw_data(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_data = 0;
  int __pyx_v_start;
  int __pyx_v_length;
  int __pyx_v_i;
  int __pyx_v_j;
  char *__pyx_v_p_rval;
  unsigned char *__pyx_v_p_data;
  PyObject *__pyx_v_rval;
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  long __pyx_2;
  int __pyx_3;
  static char *__pyx_argnames[] = {"data","start","length",0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "Oii", __pyx_argnames, &__pyx_v_data, &__pyx_v_start, &__pyx_v_length)) return 0;
  Py_INCREF(__pyx_v_data);
  __pyx_v_rval = Py_None; Py_INCREF(Py_None);

  /* "/Users/qinq/IdeaProjects/chilin/software/bx-python/lib/bx/seq/_nib.pyx":24 */
  __pyx_1 = PyString_FromStringAndSize(NULL,__pyx_v_length); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 24; goto __pyx_L1;}
  Py_DECREF(__pyx_v_rval);
  __pyx_v_rval = __pyx_1;
  __pyx_1 = 0;

  /* "/Users/qinq/IdeaProjects/chilin/software/bx-python/lib/bx/seq/_nib.pyx":26 */
  __pyx_v_p_rval = PyString_AsString(__pyx_v_rval);

  /* "/Users/qinq/IdeaProjects/chilin/software/bx-python/lib/bx/seq/_nib.pyx":27 */
  __pyx_v_p_data = ((unsigned char *)PyString_AsString(__pyx_v_data));

  /* "/Users/qinq/IdeaProjects/chilin/software/bx-python/lib/bx/seq/_nib.pyx":28 */
  __pyx_v_i = 0;

  /* "/Users/qinq/IdeaProjects/chilin/software/bx-python/lib/bx/seq/_nib.pyx":30 */
  __pyx_2 = (__pyx_v_start & 1);
  if (__pyx_2) {

    /* "/Users/qinq/IdeaProjects/chilin/software/bx-python/lib/bx/seq/_nib.pyx":32 */
    (__pyx_v_p_rval[__pyx_v_i]) = (__pyx_v_2bx_3seq_4_nib_NIB_I2C_TABLE_SECOND[(__pyx_v_p_data[0])]);

    /* "/Users/qinq/IdeaProjects/chilin/software/bx-python/lib/bx/seq/_nib.pyx":33 */
    __pyx_v_p_data = (__pyx_v_p_data + 1);

    /* "/Users/qinq/IdeaProjects/chilin/software/bx-python/lib/bx/seq/_nib.pyx":34 */
    __pyx_v_i = 1;
    goto __pyx_L2;
  }
  __pyx_L2:;

  /* "/Users/qinq/IdeaProjects/chilin/software/bx-python/lib/bx/seq/_nib.pyx":36 */
  __pyx_2 = ((__pyx_v_length - __pyx_v_i) / 2);
  for (__pyx_v_j = 0; __pyx_v_j < __pyx_2; ++__pyx_v_j) {

    /* "/Users/qinq/IdeaProjects/chilin/software/bx-python/lib/bx/seq/_nib.pyx":39 */
    (__pyx_v_p_rval[__pyx_v_i]) = (__pyx_v_2bx_3seq_4_nib_NIB_I2C_TABLE_FIRST[(__pyx_v_p_data[0])]);

    /* "/Users/qinq/IdeaProjects/chilin/software/bx-python/lib/bx/seq/_nib.pyx":40 */
    (__pyx_v_p_rval[(__pyx_v_i + 1)]) = (__pyx_v_2bx_3seq_4_nib_NIB_I2C_TABLE_SECOND[(__pyx_v_p_data[0])]);

    /* "/Users/qinq/IdeaProjects/chilin/software/bx-python/lib/bx/seq/_nib.pyx":41 */
    __pyx_v_i = (__pyx_v_i + 2);

    /* "/Users/qinq/IdeaProjects/chilin/software/bx-python/lib/bx/seq/_nib.pyx":42 */
    __pyx_v_p_data = (__pyx_v_p_data + 1);
  }

  /* "/Users/qinq/IdeaProjects/chilin/software/bx-python/lib/bx/seq/_nib.pyx":44 */
  __pyx_3 = (__pyx_v_i < __pyx_v_length);
  if (__pyx_3) {
    (__pyx_v_p_rval[__pyx_v_i]) = (__pyx_v_2bx_3seq_4_nib_NIB_I2C_TABLE_FIRST[(__pyx_v_p_data[0])]);
    goto __pyx_L5;
  }
  __pyx_L5:;

  /* "/Users/qinq/IdeaProjects/chilin/software/bx-python/lib/bx/seq/_nib.pyx":46 */
  Py_INCREF(__pyx_v_rval);
  __pyx_r = __pyx_v_rval;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  __Pyx_AddTraceback("bx.seq._nib.translate_raw_data");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_rval);
  Py_DECREF(__pyx_v_data);
  return __pyx_r;
}

static struct PyMethodDef __pyx_methods[] = {
  {"translate_raw_data", (PyCFunction)__pyx_f_2bx_3seq_4_nib_translate_raw_data, METH_VARARGS|METH_KEYWORDS, __pyx_doc_2bx_3seq_4_nib_translate_raw_data},
  {0, 0, 0, 0}
};

static void __pyx_init_filenames(void); /*proto*/

PyMODINIT_FUNC init_nib(void); /*proto*/
PyMODINIT_FUNC init_nib(void) {
  PyObject *__pyx_1 = 0;
  __pyx_init_filenames();
  __pyx_m = Py_InitModule4("_nib", __pyx_methods, 0, 0, PYTHON_API_VERSION);
  if (!__pyx_m) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; goto __pyx_L1;};
  Py_INCREF(__pyx_m);
  __pyx_b = PyImport_AddModule("__builtin__");
  if (!__pyx_b) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; goto __pyx_L1;};
  if (PyObject_SetAttrString(__pyx_m, "__builtins__", __pyx_b) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; goto __pyx_L1;};
  if (__Pyx_InitStrings(__pyx_string_tab) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; goto __pyx_L1;};

  /* "/Users/qinq/IdeaProjects/chilin/software/bx-python/lib/bx/seq/_nib.pyx":6 */
  __pyx_1 = __Pyx_Import(__pyx_n_struct, 0); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 6; goto __pyx_L1;}
  if (PyObject_SetAttr(__pyx_m, __pyx_n_struct, __pyx_1) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 6; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;

  /* "/Users/qinq/IdeaProjects/chilin/software/bx-python/lib/bx/seq/_nib.pyx":6 */
  __pyx_1 = __Pyx_Import(__pyx_n_sys, 0); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 6; goto __pyx_L1;}
  if (PyObject_SetAttr(__pyx_m, __pyx_n_sys, __pyx_1) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 6; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;

  /* "/Users/qinq/IdeaProjects/chilin/software/bx-python/lib/bx/seq/_nib.pyx":12 */
  __pyx_v_2bx_3seq_4_nib_NIB_I2C_TABLE_FIRST = __pyx_k3;

  /* "/Users/qinq/IdeaProjects/chilin/software/bx-python/lib/bx/seq/_nib.pyx":13 */
  __pyx_v_2bx_3seq_4_nib_NIB_I2C_TABLE_SECOND = __pyx_k4;

  /* "/Users/qinq/IdeaProjects/chilin/software/bx-python/lib/bx/seq/_nib.pyx":15 */
  return;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  __Pyx_AddTraceback("bx.seq._nib");
}

static char *__pyx_filenames[] = {
  "_nib.pyx",
};

/* Runtime support code */

static void __pyx_init_filenames(void) {
  __pyx_f = __pyx_filenames;
}

static int __Pyx_InitStrings(__Pyx_StringTabEntry *t) {
    while (t->p) {
        *t->p = PyString_FromStringAndSize(t->s, t->n - 1);
        if (!*t->p)
            return -1;
        if (t->i)
            PyString_InternInPlace(t->p);
        ++t;
    }
    return 0;
}

static PyObject *__Pyx_Import(PyObject *name, PyObject *from_list) {
    PyObject *__import__ = 0;
    PyObject *empty_list = 0;
    PyObject *module = 0;
    PyObject *global_dict = 0;
    PyObject *empty_dict = 0;
    PyObject *list;
    __import__ = PyObject_GetAttrString(__pyx_b, "__import__");
    if (!__import__)
        goto bad;
    if (from_list)
        list = from_list;
    else {
        empty_list = PyList_New(0);
        if (!empty_list)
            goto bad;
        list = empty_list;
    }
    global_dict = PyModule_GetDict(__pyx_m);
    if (!global_dict)
        goto bad;
    empty_dict = PyDict_New();
    if (!empty_dict)
        goto bad;
    module = PyObject_CallFunction(__import__, "OOOO",
        name, global_dict, empty_dict, list);
bad:
    Py_XDECREF(empty_list);
    Py_XDECREF(__import__);
    Py_XDECREF(empty_dict);
    return module;
}

#include "compile.h"
#include "frameobject.h"
#include "traceback.h"

static void __Pyx_AddTraceback(char *funcname) {
    PyObject *py_srcfile = 0;
    PyObject *py_funcname = 0;
    PyObject *py_globals = 0;
    PyObject *empty_tuple = 0;
    PyObject *empty_string = 0;
    PyCodeObject *py_code = 0;
    PyFrameObject *py_frame = 0;
    
    py_srcfile = PyString_FromString(__pyx_filename);
    if (!py_srcfile) goto bad;
    py_funcname = PyString_FromString(funcname);
    if (!py_funcname) goto bad;
    py_globals = PyModule_GetDict(__pyx_m);
    if (!py_globals) goto bad;
    empty_tuple = PyTuple_New(0);
    if (!empty_tuple) goto bad;
    empty_string = PyString_FromString("");
    if (!empty_string) goto bad;
    py_code = PyCode_New(
        0,            /*int argcount,*/
        0,            /*int nlocals,*/
        0,            /*int stacksize,*/
        0,            /*int flags,*/
        empty_string, /*PyObject *code,*/
        empty_tuple,  /*PyObject *consts,*/
        empty_tuple,  /*PyObject *names,*/
        empty_tuple,  /*PyObject *varnames,*/
        empty_tuple,  /*PyObject *freevars,*/
        empty_tuple,  /*PyObject *cellvars,*/
        py_srcfile,   /*PyObject *filename,*/
        py_funcname,  /*PyObject *name,*/
        __pyx_lineno,   /*int firstlineno,*/
        empty_string  /*PyObject *lnotab*/
    );
    if (!py_code) goto bad;
    py_frame = PyFrame_New(
        PyThreadState_Get(), /*PyThreadState *tstate,*/
        py_code,             /*PyCodeObject *code,*/
        py_globals,          /*PyObject *globals,*/
        0                    /*PyObject *locals*/
    );
    if (!py_frame) goto bad;
    py_frame->f_lineno = __pyx_lineno;
    PyTraceBack_Here(py_frame);
bad:
    Py_XDECREF(py_srcfile);
    Py_XDECREF(py_funcname);
    Py_XDECREF(empty_tuple);
    Py_XDECREF(empty_string);
    Py_XDECREF(py_code);
    Py_XDECREF(py_frame);
}
